repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check --fix --force-exclude src scripts tests
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude src scripts tests
        language: system
        always_run: true
        pass_filenames: false
      - id: tailwind-sorter-check
        name: tailwind-sorter-check
        entry: tailwind-sorter --config pyproject.toml --fix src
        language: system
        always_run: true
        pass_filenames: false
      - id: branch-name-and-commit-permission-check
        name: branch name and commit permission check
        entry: bash ./scripts/branch-name-check.sh
        language: system
        always_run: true
        pass_filenames: false
